#!/usr/bin/env ruby
require '/etc/puppet/dolibs/includes.rb'
cluster = args(ARGV[0], ARGV[1], ARGV[2], ARGV[3])

#Cluster organization DSL for processing server groups.
case cluster 

  when 'web'
    #web cluster
    Puppetdo.process("serviceadmin")
    Puppetdo.process("www")

  when 'blog'
    #blog cluster
    Puppetdo.process("dev-blog")
    Puppetdo.process("blog")

  when 'microapp'
    #microapp cluster
    Puppetdo.process("microapp")
    
  when 'extranet'
    #extranet cluster
    Puppetdo.process("extranet")

  when 'intranet'
    #crm cluster
    Puppetdo.process("intranet")

  when 'media'
    #media cluster
    Puppetdo.process("media")

  when 'webmedia'
    Puppetdo.process("webmedia")
 
  when 'deals'
    Puppetdo.process("deals")
  #################
  #    Logging
  ################# 
  when 'infraredis'
    Puppetdo.process("infraredis")
    Puppetdo.process("infrarediscdn")

  when 'logstash'
    Puppetdo.process("logstash")
    Puppetdo.process("logstashcdn")

  when 'logs'
    Puppetdo.process("infraredis")
    sleep 20
    Puppetdo.process("logstash")
    Puppetdo.process("infrarediscdn")
    sleep 20
    Puppetdo.process("logstashcdn")
    Puppetdo.process("log")

end
